duc/ac1/captureview/config/routes.rb
Rails.application.routes.draw do
  if Rails.application.multi_tenancy?
    constraints subdomain: 'showcase' do
      root to: 'static_pages#showcase', as: :showcase
    end

    constraints subdomain: 'login' do
      get '/signup', to: 'tenants#new'
      get '/is_available', to: 'tenants#is_available'
      
      resource :tenants, only: [:create]
    end
  end

  constraints subdomain: /.*/ do
    root to: 'static_pages#root'
    
    get '/roadmap', to: 'static_pages#roadmap'
    get '/pending-tenant', to: 'static_pages#pending_tenant'
    get '/blocked-tenant', to: 'static_pages#blocked_tenant'
    
    devise_for :users, :controllers => {
      :registrations => 'registrations',
      :sessions => 'sessions'
    }
    
    resources :tenants, only: [:show, :update]
    resources :users, only: [:index, :update]
    resources :o_auths, only: [:index, :create, :update, :destroy]
    get '/o_auths/:id/start', to: 'o_auths#start', as: :o_auth_start
    get '/o_auths/:id/callback', to: 'o_auths#callback', as: :o_auth_callback
  
    resources :posts, only: [:index, :create, :show, :update, :destroy] do
      resource :follows, only: [:create, :destroy]
      resources :follows, only: [:index]
      resource :likes, only: [:create, :destroy]
      resources :likes, only: [:index]
      resources :comments, only: [:index, :create, :update, :destroy]
      resources :post_status_changes, only: [:index]
    end
    
    resources :boards, only: [:index, :create, :update, :destroy, :show] do
      patch 'update_order', on: :collection
    end
  
    resources :post_statuses, only: [:index, :create, :update, :destroy] do
      patch 'update_order', on: :collection
    end
  
    namespace :site_settings do
      get 'general'
      get 'boards'
      get 'post_statuses'
      get 'roadmap'
      get 'users'
      get 'authentication'
    end
  end

  # Healthcheck endpoint
  get '/health', to: proc {
    Tenant.first # to make sure db works
    [200, {}, ['success']]
  }
end

duc/ac1/captureview/app/views/layouts/_alerts.html.erb
<% if notice %>
  <p class="notice container alert alert-primary"><%= notice %></p>
<% end %>

<% if alert %>
  <p class="alert container alert-danger"><%= alert %></p>
<% end %>

duc/ac1/captureview/app/views/layouts/_boards_nav_section.html.erb
<% if @tenant_setting.collapse_boards_in_header == 'always_collapse' %>
  <li class="navbar-nav nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Boards
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
      <% boards.each do |board| %>
        <li>
          <%= link_to board.name, board_path(board), class: 'dropdown-item py-2' %>
        </li>
      <% end %>
    </ul>
<% else %>
  <% boards.each do |board| %>
    <li class="nav-item<%= board.id == @board.id ? ' active' : '' unless @board.nil? %>">
      <%= link_to board.name, board_path(board), class: 'nav-link' %>
    </li>
  <% end %>
<% end %>

duc/ac1/captureview/app/views/layouts/_header.html.erb
<nav class="header">
  <div class="container">
    <%=
      link_to root_path, class: 'brand' do
        app_name = content_tag :span, @tenant.site_name
        logo = image_tag(@tenant.site_logo ? @tenant.site_logo : "", class: 'logo')

        if @tenant_setting.brand_display == "name_and_logo"
          logo + app_name
        elsif @tenant_setting.brand_display == "name_only"
          app_name
        elsif @tenant_setting.brand_display == "logo_only"
          logo
        end
      end
    %>

    <button
      class="navbarToggler"
      type="button"
      data-toggle="collapse"
      data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="boardsNav">
        <% if @tenant_setting.show_roadmap_in_header %>
          <li class="nav-item<%= (current_page?(roadmap_path) or (@tenant_setting.root_board_id == 0 and current_page?(root_path))) ? ' active' : '' %>">
            <%= link_to "Roadmap", roadmap_path, class: 'nav-link' %>
          </li>
        <% end %>
        
        <% if (user_signed_in?) then %>
          <div id="boards_nav_section">
            <%= render 'layouts/boards_nav_section', boards: @boards unless @boards.nil? %>
          </div>
        <% end %>
      </ul>

      <ul class="profileNav">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="profileToggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag(current_user.gravatar_url, class: 'gravatar', alt: current_user.full_name, size: 24) %>
              <span class="fullname"><%= current_user.full_name %></span>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <% if current_user.moderator? %>
                <%=
                  link_to t('header.menu.site_settings'),
                    current_user.admin? ? site_settings_general_path : site_settings_users_path,
                    class: 'dropdown-item'
                %>
                <div class="dropdown-divider"></div>
              <% end %>

              <%= link_to t('header.menu.profile_settings'), edit_user_registration_path, class: 'dropdown-item' %>
              <div class="dropdown-divider"></div>

              <%= button_to t('header.menu.sign_out'), destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to t('header.log_in'), new_user_session_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

duc/ac1/captureview/app/views/layouts/_set_js_locale.html.erb
<script type="text/javascript">
  // Used to set I18n-js locale to Rails locale
  // Variable used in javascript/translations/index.js.erb
  
  var LOCALE = "<%= I18n.locale %>";
</script>

duc/ac1/captureview/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @tenant ? @tenant.site_name : @page_title %></title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="turbolinks-cache-control" content="no-cache">

    <%= render 'layouts/set_js_locale' %>

    <%= javascript_include_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <% if @tenant %>
      <%= render 'layouts/header' %>
    <% end %>
    
    <%= render 'layouts/alerts' %>
    
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

duc/ac1/captureview/app/views/layouts/user_mailer.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  </head>
  <body>
    <p><%= t('mailers.user.opening_greeting') %></p>

    <div><%= yield %></div>
    
    <p><%= t('mailers.user.closing_greeting') %></p>

    <footer>
      <%=
        link_to(
          t('mailers.user.unsubscribe'),
          add_subdomain_to(method(:edit_user_registration_url))
        )
      %>.
    </footer>
  </body>
</html>

duc/ac1/captureview/app/views/layouts/user_mailer.text.erb
<%= yield %>